name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known_hosts
        run: ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: ssh -T -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} echo "SSH Connection Successful"

      - name: Deploy application
        run: |
          ssh -T -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
          set -e
          cd /home/${{ secrets.DO_USER }}/www.planix.com.tr
          git pull origin main
          npm run clean
          npm install
          npm run build
          pm2 restart www.planix.com.tr || pm2 start npm --name www.planix.com.tr -- start
          EOF

      - name: Deployment completed
        run: echo "Deployment to DigitalOcean completed successfully!"
