name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            #!/usr/bin/env bash
            set -e
            cd /home/${{ secrets.SERVER_USER }}/www.planix.com.tr
            git pull origin main
            docker compose -f docker-compose.yml build landing-prod
            docker compose -f docker-compose.yml down landing-prod
            docker compose -f docker-compose.yml up -d landing-prod --remove-orphans
